### PR TITLE
Augmented the Decimal's internal implementation with Decimal4j

### PR DESCRIPTION
**Pull request by davassi**
Augmented the Decimal's internal implementation with Decimal4j

Changes proposed in this pull request:
- Added Decimal4j dependency in pom.xml
- Replaced BigDecimal delegate with Decimal8f
- Changed one expected value on assert on a CCII indicator unit test

### CODE REVIEW

**Comment by davassi** [comment]
Travis doesn't build as java.lang.UnsupportedClassVersionError: org/decimal4j/api/Decimal : Unsupported major.minor version 51.0

**Comment by gcauchis** [comment]
Yes Decimal4J is a java 7 library. Taj4 is for now compatible with java 6. So the build with jdk 6 cannot pass.

**Comment by davassi** [comment]
Public support for java 6 has ended last December :)

**Comment by mdeverdelhan** [comment]
About decimal4j, I replied in #28.

About Java 6, you are right. However some of our users are still using it.
We might drop its support (even Java 7 if needed) if we had a real reason to do so (for instance, an efficient decimal class). But for now, since decimal4j did not convince me, we don't have one. :/

**Pull request closed without merging**
