### PR TITLE
Analysis over multiple trading records

### PR DESCRIPTION
**Pull request by sirolf2009**
Analysis so far can only be applied to a single trading record. If you want to combine long and short performance, or performance over multiple markets, you would have to manually combine the results from the AnalysisCriteria in order to get an overview of peformance

Changes proposed in this pull request:
- AnalysisCriterion works with Trad**es**Record instead, an interface that is basically an Iterable of Trades
- Trad**ing**Record implements Trad**es**Record, so that you can apply analysis on it
- A new class, called PortFolio, implements TradesRecord and acts as a collection of TradingRecords, to perform analysis over multiple TradingRecords

### CODE REVIEW

**Comment by sirolf2009** [comment]
@mdeverdelhan any update on this?

**Comment by TheCookieLab** [comment]
Just my opinion but it seems the use case is not general enough to warrant introducing the additional complexity to the base framework. The functionality can be achieved in your using code without having to modify the base library.

**Comment by sirolf2009** [comment]
True, but being able to do it doesn't mean that it's supported.
In my opinion, being able to calculate, let's say, a average profitable trades from both your shorts and long sounds like a very basic thing. Without this pull though, you couldn't use the built-in ```AverageProfitableTradesCriterion``` because summing/averaging 2 averages won't result in the actual average. Which means that you'd have to implement your own class that does it for you, which kind of defeats the purpose of libraries

**Comment by mdeverdelhan** [comment]
Sorry for the long time. I was hesitating (and trying to find time to think about it.)

I understand the use case. But as @TheCookieLab said it is not worthwhile. You are coming with an additional complexity that has to be documented, maintained, etc. for a very specific functionality (relatively to the current scope of the lib).

At least I think it should be part of a far stronger redesign of ta4j. IMO, analysis over multiple trading record imply trading on multiple time series. Adding the possibility to trade on multiple time series raises many questions and problems. I already said that if I have nothing against I am not able to find enough time to refactor the whole stuff in that way.

**Comment by sirolf2009** [comment]
Alright, fair enough. Any insights on combining long/short performance though? I understand that analysis over multiple timeseries would need to be put in place nicer, but doing a long simulation and short simulation without ending up with 2 tradingrecords sounds like a pretty core feature

**Pull request closed without merging**
