### PR TITLE
Update to AverageTrueRange Indicator

### PR DESCRIPTION
**Pull request by whitfa99**
The initialised value of this indicator is set to 1.  Better to initialise it with the first value of the underlying TrueRange Indicator?

### CODE REVIEW

**Comment by mdeverdelhan** [comment]
Thank you but the build failed. You will have to update the tests.

**Comment by whitfa99** [comment]
Sorry - first time at this.  I'll try compiling the whole thing.

**Comment by mdeverdelhan** [comment]
Sorry but still unacceptable. :/
ATR is used by some other indicators; they have to be updated too.
Don't forget to execute a `mvn clean install` before committing.

**Comment by whitfa99** [comment]
I saw that. Sorry, yes I was going through the tests to see if I could redo
them to accommodate the change. A bit of a can of worms I opened. Will try
again tomorrow.

Thanks

**Pull request closed without merging**
